export const chips = [
  "Lesson Planning",
  "EdTech Tools",
  "Student Engagement",
  "Assessment Strategies",
  "Personalization",
  "Analytics",
  "Collaboration",
  "Parents",
  "Security & Compliance",
  "AI-Powered Learning",
  "Curriculum Design",
  "Classroom Management",
  "Blended Learning",
  "Remote Learning",
  "Gamification",
  "Learning Outcomes",
  "Teacher Professional Development",
  "Special Education",
  "STEM Education",
  "Language Learning",
  "Early Childhood Education",
  "Higher Education",
  "Digital Literacy",
  "Student Wellbeing",
  "Peer Learning",
  "Project-Based Learning",
  "Feedback & Grading",
  "Learning Management Systems",
  "Content Creation",
  "Data Privacy"
]
