/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./components/landing/about/AboutPage.vue')['default']
    BlogHomePage: typeof import('./components/blogs/BlogsHomePage.vue')['default']
    BlogsArticlePage: typeof import('./components/landing/blogs/BlogsArticlePage.vue')['default']
    BlogsHomePage: typeof import('./components/landing/blogs/BlogsHomePage.vue')['default']
    BrandingPage: typeof import('./components/landing/branding/BrandingPage.vue')['default']
    ContactPage: typeof import('./components/landing/contact/ContactPage.vue')['default']
    CustomBreadcrumb: typeof import('./components/commons/CustomBreadcrumb.vue')['default']
    ForumsCategory: typeof import('./components/landing/forums/ForumsCategory.vue')['default']
    ForumsHome: typeof import('./components/landing/forums/ForumsHome.vue')['default']
    ForumsThread: typeof import('./components/landing/forums/ForumsThread.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeFooter: typeof import('./components/landing/home/HomeFooter.vue')['default']
    HomeHeader: typeof import('./components/landing/home/HomeHeader.vue')['default']
    HomePage: typeof import('./components/landing/home/HomePage.vue')['default']
    LabelledContainer: typeof import('./components/commons/LabelledContainer.vue')['default']
    LoginPage: typeof import('./components/auth/login/LoginPage.vue')['default']
    MissionsPage: typeof import('./components/landing/missions/MissionsPage.vue')['default']
    PricingPage: typeof import('./components/landing/pricing/PricingPage.vue')['default']
    PrivacyPolicyPage: typeof import('./components/landing/privacy/PrivacyPolicyPage.vue')['default']
    RegisterPage: typeof import('./components/auth/register/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamPage: typeof import('./components/landing/teams/TeamPage.vue')['default']
    TermsOfServicePage: typeof import('./components/landing/terms/TermsOfServicePage.vue')['default']
  }
}
