/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/app': RouteRecordInfo<'/app', '/app', Record<never, never>, Record<never, never>>,
    '/blogs/': RouteRecordInfo<'/blogs/', '/blogs', Record<never, never>, Record<never, never>>,
    '/blogs/article/[id]': RouteRecordInfo<'/blogs/article/[id]', '/blogs/article/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/branding/': RouteRecordInfo<'/branding/', '/branding', Record<never, never>, Record<never, never>>,
    '/contact/': RouteRecordInfo<'/contact/', '/contact', Record<never, never>, Record<never, never>>,
    '/forums/': RouteRecordInfo<'/forums/', '/forums', Record<never, never>, Record<never, never>>,
    '/forums/category/[id]': RouteRecordInfo<'/forums/category/[id]', '/forums/category/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/forums/thread/[id]': RouteRecordInfo<'/forums/thread/[id]', '/forums/thread/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/missions/': RouteRecordInfo<'/missions/', '/missions', Record<never, never>, Record<never, never>>,
    '/pricing/': RouteRecordInfo<'/pricing/', '/pricing', Record<never, never>, Record<never, never>>,
    '/privacy/': RouteRecordInfo<'/privacy/', '/privacy', Record<never, never>, Record<never, never>>,
    '/register/': RouteRecordInfo<'/register/', '/register', Record<never, never>, Record<never, never>>,
    '/teams/': RouteRecordInfo<'/teams/', '/teams', Record<never, never>, Record<never, never>>,
    '/terms/': RouteRecordInfo<'/terms/', '/terms', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/about/index.vue': {
      routes: '/about/'
      views: never
    }
    'src/pages/app.vue': {
      routes: '/app'
      views: never
    }
    'src/pages/blogs/index.vue': {
      routes: '/blogs/'
      views: never
    }
    'src/pages/blogs/article/[id].vue': {
      routes: '/blogs/article/[id]'
      views: never
    }
    'src/pages/branding/index.vue': {
      routes: '/branding/'
      views: never
    }
    'src/pages/contact/index.vue': {
      routes: '/contact/'
      views: never
    }
    'src/pages/forums/index.vue': {
      routes: '/forums/'
      views: never
    }
    'src/pages/forums/category/[id].vue': {
      routes: '/forums/category/[id]'
      views: never
    }
    'src/pages/forums/thread/[id].vue': {
      routes: '/forums/thread/[id]'
      views: never
    }
    'src/pages/home/index.vue': {
      routes: '/home/'
      views: never
    }
    'src/pages/login/index.vue': {
      routes: '/login/'
      views: never
    }
    'src/pages/missions/index.vue': {
      routes: '/missions/'
      views: never
    }
    'src/pages/pricing/index.vue': {
      routes: '/pricing/'
      views: never
    }
    'src/pages/privacy/index.vue': {
      routes: '/privacy/'
      views: never
    }
    'src/pages/register/index.vue': {
      routes: '/register/'
      views: never
    }
    'src/pages/teams/index.vue': {
      routes: '/teams/'
      views: never
    }
    'src/pages/terms/index.vue': {
      routes: '/terms/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
